### ISSUE TITLE
Does media query work on mobile?

### ISSUE THREAD

**Issue by constancebunch** [kristerkari/react-native-css-modules-with-media-queries-example#2]
I have tried to download the project and test around, the media query works on web but mobile not.

**Comment by kristerkari** [comment]
Thanks @constancebunch ! What exactly do you mean by not working in mobile, are referring to React Native or a mobile web browser?

Let me know more details, I want everything to work :)

**Comment by kristerkari** [comment]
If you look at the screenshots, this is how it should look on mobile (Web and React Native):
https://github.com/kristerkari/react-native-css-modules-with-media-queries-example#screenshots

**Comment by kristerkari** [comment]
I actually noticed that the app was not working on Android Stock browser (4.4-5.0) because of newer React versions using some ES6 methods and requiring polyfills for those, so made a fix and now the app works on Android Stock, except that the rendering is a bit broken:
https://github.com/kristerkari/react-native-css-modules-with-media-queries-example/commit/e3b4a248e75698afccf414ab250822cdff200b21

**Comment by kristerkari** [comment]
This example app should work on Android stock browser now.

Let me know if it does not work. :)
